# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booz',
            options={'ordering': ['-created_on'], 'verbose_name': 'owner', 'verbose_name_plural': 'owners'},
        ),
    ]
