# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0002_auto_20170710_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booz',
            options={'ordering': ['-created_on'], 'verbose_name': 'booz', 'verbose_name_plural': 'boozs'},
        ),
        migrations.AlterField(
            model_name='booz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boozs', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
