# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0003_auto_20170710_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booz',
            name='via',
            field=models.URLField(blank=True, verbose_name='(optional)web address for further verification(e.g http://bobos $ booboos.com)'),
        ),
    ]
