# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0006_auto_20170711_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booz',
            name='subject_matter',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
