# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0007_auto_20170712_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booz', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
