# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0009_auto_20170712_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='booz',
            name='via',
            field=models.URLField(blank=True, verbose_name='(optional)web address for further verification(e.g http://bobos-booboos.com)'),
        ),
        migrations.AddField(
            model_name='booz',
            name='tags',
            field=models.ManyToManyField(blank=True, to='booz.Tag'),
        ),
    ]
