# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0012_auto_20170714_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='approved_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='blat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='booz.Booz'),
        ),
    ]
