# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booz', '0013_auto_20170714_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='blat',
            new_name='booz',
        ),
    ]
